
openapi: 3.0.0

info:
  title: Public Project Back-end
  version: 1.0.0
servers:
  - url: http://localhost:3000/
    description: Main server with production functions
  - url: http://localhost:4000/
    description: Test server without database. For tests only 

paths:
  /user:
    post: 
      tags: 
      - "Users"
      summary: "Adding new user"
      requestBody: 
        description: "Adding user info"
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/User"   
      responses:
        200: 
          description: "User successfully added"
        415: 
          description: "Invalid body schema"
        406: 
          description: "Login is already reserved"
        500: 
          description: "Internal server error"
        

components:
  schemas:
    User: 
      type: 'object'
      properties:
        login: 
          type: 'string'
        password: 
          type: 'string'
        city: 
          type: 'string'
        age: 
          type: 'number'
        mail: 
          type: 'string'
          
        
externalDocs:
  description: "Online swagger viewer"
  url: "https://editor.swagger.io/"
  